#!/usr/bin/env python
'''
@author: jonathanfriedman
Script for making simulated datasets used to get pseudo p-values.

'''
import os

# isort: off
import sparcc  # noqa: F401  (sets OPENSSL_CONF before pandas pulls in pyarrow)
# isort: on

import numpy as np
import pandas as pd

from sparcc.io_methods import read_txt, write_txt


def permute_w_replacement(frame: pd.DataFrame | np.ndarray, axis: int = 0,
                          rng: np.random.Generator | None = None):
    '''
    Resample the frame values with replacement along the given axis.
    Create a simulated dataset where the count of each component (column)
    in each sample (row) is randomly drawn, with replacement, from all the
    counts of that component in all samples.

    Parameters
    ----------
    frame : DataFrame or Numpy Array
        Frame to resample.
    axis : {0, 1}
        - 0 - Resample each column's values across rows (default)
        - 1 - Resample each row's values across columns
    rng : numpy Generator, optional
        Random generator to use (a fresh default_rng() if not given).

    Returns
    -------
    Resampled frame (new instance, same type, index and columns as the input).
    '''
    if axis not in (0, 1):
        raise ValueError(f'axis must be 0 or 1, got {axis}')
    if rng is None:
        rng = np.random.default_rng()

    values = np.asarray(frame)
    n = values.shape[axis]
    # Independent row (or column) indices for every column (or row)
    idx = rng.integers(0, n, size=values.shape)
    resampled = np.take_along_axis(values, idx, axis=axis)

    if isinstance(frame, pd.DataFrame):
        return pd.DataFrame(resampled, index=frame.index, columns=frame.columns)
    return resampled


def make_bootstraps(counts, nperm, perm_template, outpath='./', iprint=0):
    '''
    Make n simulated datasets used to get pseudo p-values.
    Simulated datasets are generated by assigning each OTU in each sample
    an abundance that is randomly drawn (w. replacement) from the
    abundances of the OTU in all samples.
    Simulated datasets are written out as delimited text files.

    Parameters
    ----------
    counts : DataFrame
        Counts (samples as rows, components as columns).
    nperm : int
        Number of permutations to produce.
    perm_template : str
        Template for the permuted data file names.
        Should not include the path, which is specified using the
        outpath parameter.
        The iteration number is indicated with a "#".
        For example: 'counts.permuted_#.csv'
    outpath : str (default './')
        The path to which permuted data will be written.
        If not provided files will be written to the cwd.
    iprint : int (default = 0)
        The interval at which iteration number is printed out.
        If iprint<=0 no printouts are made.
    '''
    os.makedirs(outpath, exist_ok=True)
    rng = np.random.default_rng()

    for i in range(nperm):
        if iprint > 0 and not i % iprint:
            print(i)
        # Resample each component's counts across samples
        counts_perm = permute_w_replacement(counts, axis=0, rng=rng)

        outfile = os.path.join(outpath, perm_template.replace('#', '%d' % i))
        #The output is written
        write_txt(counts_perm, outfile,index=True)

def main(counts_file, nperm, perm_template, outpath='./'):
    '''
    Make n simulated datasets used to get pseudo p-values.
    Simulated datasets are generated by assigning each OTU in each sample
    an abundance that is randomly drawn (w. replacement) from the
    abundances of the OTU in all samples.
    Simulated datasets are written out as csv files.
    '''
    if perm_template is None:
        perm_template = os.path.basename(counts_file) + '.permuted_#.csv'
    ## read counts data
    counts = read_txt(counts_file, index_col=0)
    if counts.shape[0] == 0:
        # A .txt file that is actually comma-separated; retry with sep=','
        counts = read_txt(counts_file, sep=',', index_col=0)
    if counts.shape[0] == 0:
        raise ValueError(f'Could not parse any samples from "{counts_file}".')

    ## make permutated data
    print("Permutations")
    make_bootstraps(counts, nperm, perm_template, outpath=outpath)

if __name__ == '__main__':

    ## parse input arguments
    from optparse import OptionParser
    usage  = ('Make n simulated datasets used to get pseudo p-values.\n'
              'Simulated datasets are generated by assigning each OTU in each sample an abundance that is randomly drawn (w. replacement) from the abundances of the OTU in all samples.\n'
              'Simulated datasets are written out as delimited text files.\n'
              '\n'
              'Usage:   python MakeBootstraps.py counts_file [options]\n'
              'Example: python MakeBootstraps.py example/fake_data.txt -n 5 -t permutation_#.csv -p example/pvals/')
    parser = OptionParser(usage)
    parser.add_option("-n", dest="n", default=100, type = 'int',
                      help="Number of simulated datasets to create (100 default).")
    parser.add_option("-t", "--template", dest="perm_template", default=None, type = 'str',
                      help="The template for the permuted data file names.\n"
                           "Should not include the path, which is specified using the -p option.\n"
                           'The iteration number is indicated with a "#".\n'
                           "For example: 'counts.permuted_#.csv'. "
                           "If not provided a '.permuted_#.csv' suffix will be added to the counts file name.\n")
    parser.add_option("-p", "--path", dest="outpath", default='./', type = 'str',
                      help="The path to which permuted data will be written.\n"
                           "If not provided files will be written to the cwd.\n")
    (options, args) = parser.parse_args()
    if len(args) != 1:
        parser.error('Expected exactly one counts_file argument.')
    counts_file     = args[0]
    n               = options.n
    outpath         = options.outpath
    perm_template   = options.perm_template

    main(counts_file, n, perm_template, outpath)

